/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,vue,js,ts,jsx,tsx}"],
  theme: {
    colors: {
      baggrundsfarve: "#F9D7DE",
      tekstfarve: "#471C24",
      hover: "#594ABF",
      checkbox: "#A2D2FF",
      hover2: "#FFB6E1",
      knapfarve: "#FFFAF1",
      tekstfelt: "#FEF1F1",
      tekstfelt_skrift: "#AAAAAB",
      afvis_cookies: "#F23333",
      tillad_cookies: "#7EF089",
      grøn: "#3c5540",
      gul: "#ce841b",
      hvid: "#f7f0de",
      sort: "#000000",
      lavendel: "#cc97de",
      turkis: "#3ea4b0",
      blå: "#4f77ea",
      rosa: "#fb9f9f",
      mørkegrå: "#8f8a8a",
      grå: "#d9d9d9",
      brun: "#5a3d2b",
    },
    extend: {},
  },
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")],
};
